language: node_js
node_js:
- '12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- cp .travis/id_rsa  ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add -K ~/.ssh/id_rsa | 
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "zhio"
- git config --global user.email 1406816741@qq.com
install:
- npm install hexo-cli -g
- npm install
script:
- npm run deploy
